[build]
  base = "apps/bench"
  command = "cd ../.. && bun install && bun x tsc --project packages/quantumjs && cd apps/bench && bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
